name: Docker-Coq CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'fiplus/coq/coq-fiplus.opam'
          coq_version: ${{ matrix.coq_version }}
          before_install: |
            startGroup "Add coq-extra-dev repo"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
            endGroup
            startGroup "Print opam config"
              opam config list; opam repo list; opam list
            endGroup
